# Generated by Django 4.1.3 on 2023-11-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="title",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
