# Generated by Django 4.1.3 on 2023-11-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="image",
            field=models.ImageField(upload_to="courses/%Y/%m/%d/"),
        ),
    ]
