# Generated by Django 4.1.3 on 2023-11-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
